#!/usr/bin/env python3
"""
build.py — converts export-list.xlsx into data.js for the LSPF dashboard.
Run locally before pushing:
    python3 build.py
"""

import json
import pandas as pd

XLSX          = "export-list.xlsx"
OUT           = "data.js"
CAMPAIGN_YEAR = 2026

df = pd.read_excel(XLSX)
df.columns = [c.strip() for c in df.columns]

# ── Parse dates ───────────────────────────────────────────────────────────────
df["submitted_dt"]   = pd.to_datetime(df["Submitted at"], utc=True)
df["submitted_date"] = df["submitted_dt"].dt.date.astype(str)   # "YYYY-MM-DD"

# ── Compute age (integer) ─────────────────────────────────────────────────────
def birth_year(s):
    try:
        return int(str(s).strip()[-4:])
    except Exception:
        return None

df["birth_year"] = df["Birthday"].apply(birth_year)
df["age"]        = CAMPAIGN_YEAR - df["birth_year"]

# ── Build records list ────────────────────────────────────────────────────────
cols = {"submitted_date": "date", "Gender": "gender", "age": "age",
        "Nationality": "nationality", "Country": "country"}
records_df = df[list(cols.keys())].rename(columns=cols).copy()
records_df["gender"]      = records_df["gender"].str.lower().str.strip()
records_df["nationality"] = records_df["nationality"].str.upper().str.strip()
records_df["country"]     = records_df["country"].str.upper().str.strip()
records_df = records_df.dropna(subset=["date", "gender"])
records_df["age"] = records_df["age"].apply(
    lambda x: int(x) if pd.notna(x) and str(x) != "nan" else None
)

records = records_df.to_dict(orient="records")

# ── Write data.js ─────────────────────────────────────────────────────────────
js = "// Auto-generated by build.py — do not edit manually.\n"
js += "const DATA = " + json.dumps({"records": records}, indent=2) + ";\n"

with open(OUT, "w") as f:
    f.write(js)

dates = sorted(set(r["date"] for r in records))
print(f"✓ {OUT} written — {len(records)} submissions, {len(dates)} days ({dates[0]} → {dates[-1]})")
