// Auto-generated by build.py — do not edit manually.
const DATA = {
  "records": [
    {
      "date": "2026-04-04",
      "gender": "male",
      "age": 59,
      "nationality": "FR",
      "country": "FR"
    },
    {
      "date": "2026-04-04",
      "gender": "female",
      "age": 46,
      "nationality": "CA",
      "country": "CA"
    },
    {
      "date": "2026-04-05",
      "gender": "male",
      "age": 30,
      "nationality": "BE",
      "country": "BE"
    },
    {
      "date": "2026-04-06",
      "gender": "male",
      "age": 44,
      "nationality": "RO",
      "country": "RO"
    },
    {
      "date": "2026-04-05",
      "gender": "male",
      "age": 52,
      "nationality": "PT",
      "country": "PT"
    },
    {
      "date": "2026-04-08",
      "gender": "male",
      "age": 57,
      "nationality": "DE",
      "country": "DE"
    },
    {
      "date": "2026-04-09",
      "gender": "male",
      "age": 59,
      "nationality": "CZ",
      "country": "CZ"
    },
    {
      "date": "2026-04-08",
      "gender": "female",
      "age": 64,
      "nationality": "GB",
      "country": "GB"
    },
    {
      "date": "2026-04-08",
      "gender": "male",
      "age": 38,
      "nationality": "DE",
      "country": "DE"
    },
    {
      "date": "2026-04-08",
      "gender": "female",
      "age": 41,
      "nationality": "BR",
      "country": "FR"
    },
    {
      "date": "2026-04-08",
      "gender": "male",
      "age": 45,
      "nationality": "DE",
      "country": "DE"
    },
    {
      "date": "2026-04-09",
      "gender": "male",
      "age": 63,
      "nationality": "US",
      "country": "US"
    },
    {
      "date": "2026-04-09",
      "gender": "female",
      "age": 47,
      "nationality": "MX",
      "country": "MX"
    },
    {
      "date": "2026-04-06",
      "gender": "male",
      "age": 51,
      "nationality": "DE",
      "country": "DE"
    },
    {
      "date": "2026-04-06",
      "gender": "male",
      "age": 56,
      "nationality": "NZ",
      "country": "NZ"
    },
    {
      "date": "2026-04-09",
      "gender": "male",
      "age": 58,
      "nationality": "IT",
      "country": "IT"
    },
    {
      "date": "2026-04-09",
      "gender": "male",
      "age": 53,
      "nationality": "GB",
      "country": "GB"
    },
    {
      "date": "2026-04-07",
      "gender": "male",
      "age": 65,
      "nationality": "DE",
      "country": "ES"
    },
    {
      "date": "2026-04-07",
      "gender": "female",
      "age": 54,
      "nationality": "FR",
      "country": "FR"
    },
    {
      "date": "2026-04-07",
      "gender": "female",
      "age": 69,
      "nationality": "PT",
      "country": "PT"
    },
    {
      "date": "2026-04-07",
      "gender": "male",
      "age": 67,
      "nationality": "BR",
      "country": "BR"
    },
    {
      "date": "2026-04-08",
      "gender": "female",
      "age": 28,
      "nationality": "PT",
      "country": "PT"
    },
    {
      "date": "2026-04-07",
      "gender": "female",
      "age": 60,
      "nationality": "CA",
      "country": "CA"
    },
    {
      "date": "2026-04-08",
      "gender": "female",
      "age": 56,
      "nationality": "PL",
      "country": "GB"
    },
    {
      "date": "2026-04-09",
      "gender": "female",
      "age": 27,
      "nationality": "BR",
      "country": "BR"
    },
    {
      "date": "2026-04-03",
      "gender": "male",
      "age": 68,
      "nationality": "DE",
      "country": "DE"
    },
    {
      "date": "2026-04-05",
      "gender": "male",
      "age": 45,
      "nationality": "DE",
      "country": "DE"
    },
    {
      "date": "2026-04-03",
      "gender": "male",
      "age": 47,
      "nationality": "DE",
      "country": "FR"
    },
    {
      "date": "2026-04-07",
      "gender": "female",
      "age": 33,
      "nationality": "MX",
      "country": "MX"
    },
    {
      "date": "2026-04-04",
      "gender": "female",
      "age": 40,
      "nationality": "US",
      "country": "US"
    },
    {
      "date": "2026-04-06",
      "gender": "male",
      "age": 48,
      "nationality": "BE",
      "country": "BE"
    },
    {
      "date": "2026-04-02",
      "gender": "female",
      "age": 33,
      "nationality": "RO",
      "country": "RO"
    },
    {
      "date": "2026-04-02",
      "gender": "male",
      "age": 35,
      "nationality": "PH",
      "country": "PH"
    },
    {
      "date": "2026-04-02",
      "gender": "male",
      "age": 52,
      "nationality": "PT",
      "country": "PT"
    },
    {
      "date": "2026-04-07",
      "gender": "male",
      "age": 55,
      "nationality": "BE",
      "country": "BE"
    },
    {
      "date": "2026-04-02",
      "gender": "female",
      "age": 60,
      "nationality": "FR",
      "country": "FR"
    },
    {
      "date": "2026-04-06",
      "gender": "female",
      "age": 41,
      "nationality": "BR",
      "country": "BR"
    },
    {
      "date": "2026-04-02",
      "gender": "male",
      "age": 36,
      "nationality": "GB",
      "country": "GB"
    },
    {
      "date": "2026-04-06",
      "gender": "male",
      "age": 31,
      "nationality": "IN",
      "country": "NL"
    },
    {
      "date": "2026-04-02",
      "gender": "male",
      "age": 69,
      "nationality": "US",
      "country": "US"
    },
    {
      "date": "2026-04-03",
      "gender": "female",
      "age": 30,
      "nationality": "US",
      "country": "US"
    },
    {
      "date": "2026-04-03",
      "gender": "male",
      "age": 48,
      "nationality": "BR",
      "country": "US"
    },
    {
      "date": "2026-04-03",
      "gender": "male",
      "age": 41,
      "nationality": "VE",
      "country": "VE"
    },
    {
      "date": "2026-04-03",
      "gender": "male",
      "age": 68,
      "nationality": "PR",
      "country": "PR"
    },
    {
      "date": "2026-04-08",
      "gender": "male",
      "age": 31,
      "nationality": "FR",
      "country": "FR"
    },
    {
      "date": "2026-04-06",
      "gender": "male",
      "age": 36,
      "nationality": "IT",
      "country": "IT"
    },
    {
      "date": "2026-04-05",
      "gender": "female",
      "age": 23,
      "nationality": "PT",
      "country": "PT"
    },
    {
      "date": "2026-04-02",
      "gender": "female",
      "age": 38,
      "nationality": "IT",
      "country": "IT"
    },
    {
      "date": "2026-04-08",
      "gender": "female",
      "age": 47,
      "nationality": "GB",
      "country": "GB"
    },
    {
      "date": "2026-04-02",
      "gender": "male",
      "age": 57,
      "nationality": "ES",
      "country": "ES"
    },
    {
      "date": "2026-04-02",
      "gender": "female",
      "age": 75,
      "nationality": "US",
      "country": "US"
    },
    {
      "date": "2026-04-02",
      "gender": "female",
      "age": 56,
      "nationality": "ES",
      "country": "ES"
    },
    {
      "date": "2026-04-02",
      "gender": "female",
      "age": 40,
      "nationality": "PL",
      "country": "PL"
    },
    {
      "date": "2026-04-02",
      "gender": "male",
      "age": 40,
      "nationality": "GB",
      "country": "GB"
    },
    {
      "date": "2026-04-02",
      "gender": "male",
      "age": 42,
      "nationality": "ES",
      "country": "ES"
    },
    {
      "date": "2026-04-02",
      "gender": "male",
      "age": 39,
      "nationality": "PT",
      "country": "PT"
    },
    {
      "date": "2026-04-02",
      "gender": "male",
      "age": 35,
      "nationality": "KR",
      "country": "AU"
    },
    {
      "date": "2026-04-02",
      "gender": "female",
      "age": 51,
      "nationality": "IL",
      "country": "IL"
    },
    {
      "date": "2026-04-02",
      "gender": "female",
      "age": 46,
      "nationality": "HK",
      "country": "HK"
    },
    {
      "date": "2026-04-02",
      "gender": "male",
      "age": 89,
      "nationality": "US",
      "country": "US"
    },
    {
      "date": "2026-04-02",
      "gender": "male",
      "age": 24,
      "nationality": "CN",
      "country": "CN"
    },
    {
      "date": "2026-04-02",
      "gender": "male",
      "age": 39,
      "nationality": "PT",
      "country": "PT"
    },
    {
      "date": "2026-04-02",
      "gender": "male",
      "age": 62,
      "nationality": "CA",
      "country": "CA"
    },
    {
      "date": "2026-04-02",
      "gender": "female",
      "age": 32,
      "nationality": "IT",
      "country": "IT"
    },
    {
      "date": "2026-04-03",
      "gender": "male",
      "age": 52,
      "nationality": "IT",
      "country": "IT"
    },
    {
      "date": "2026-04-03",
      "gender": "male",
      "age": 64,
      "nationality": "BE",
      "country": "BE"
    },
    {
      "date": "2026-04-03",
      "gender": "male",
      "age": 63,
      "nationality": "DE",
      "country": "CH"
    },
    {
      "date": "2026-04-03",
      "gender": "female",
      "age": 77,
      "nationality": "US",
      "country": "MX"
    },
    {
      "date": "2026-04-04",
      "gender": "male",
      "age": 45,
      "nationality": "PT",
      "country": "PT"
    },
    {
      "date": "2026-04-04",
      "gender": "male",
      "age": 39,
      "nationality": "CY",
      "country": "IE"
    },
    {
      "date": "2026-04-05",
      "gender": "male",
      "age": 38,
      "nationality": "PT",
      "country": "PT"
    },
    {
      "date": "2026-04-05",
      "gender": "female",
      "age": 39,
      "nationality": "ZA",
      "country": "SG"
    },
    {
      "date": "2026-04-05",
      "gender": "male",
      "age": 37,
      "nationality": "AT",
      "country": "AT"
    },
    {
      "date": "2026-04-05",
      "gender": "male",
      "age": 52,
      "nationality": "GB",
      "country": "GB"
    },
    {
      "date": "2026-04-06",
      "gender": "male",
      "age": 74,
      "nationality": "US",
      "country": "US"
    },
    {
      "date": "2026-04-06",
      "gender": "male",
      "age": 37,
      "nationality": "SG",
      "country": "SG"
    },
    {
      "date": "2026-04-06",
      "gender": "female",
      "age": 58,
      "nationality": "ES",
      "country": "ES"
    },
    {
      "date": "2026-04-06",
      "gender": "male",
      "age": 50,
      "nationality": "IT",
      "country": "IT"
    },
    {
      "date": "2026-04-06",
      "gender": "male",
      "age": 42,
      "nationality": "IT",
      "country": "IT"
    },
    {
      "date": "2026-04-06",
      "gender": "male",
      "age": 71,
      "nationality": "IE",
      "country": "FR"
    },
    {
      "date": "2026-04-06",
      "gender": "male",
      "age": 76,
      "nationality": "US",
      "country": "US"
    },
    {
      "date": "2026-04-06",
      "gender": "male",
      "age": 38,
      "nationality": "PT",
      "country": "PT"
    },
    {
      "date": "2026-04-06",
      "gender": "male",
      "age": 37,
      "nationality": "FR",
      "country": "CA"
    },
    {
      "date": "2026-04-06",
      "gender": "male",
      "age": 30,
      "nationality": "KR",
      "country": "KR"
    },
    {
      "date": "2026-04-06",
      "gender": "male",
      "age": 32,
      "nationality": "BR",
      "country": "PT"
    },
    {
      "date": "2026-04-07",
      "gender": "male",
      "age": 48,
      "nationality": "US",
      "country": "US"
    },
    {
      "date": "2026-04-07",
      "gender": "male",
      "age": 68,
      "nationality": "US",
      "country": "US"
    },
    {
      "date": "2026-04-07",
      "gender": "male",
      "age": 52,
      "nationality": "ID",
      "country": "ID"
    },
    {
      "date": "2026-04-07",
      "gender": "female",
      "age": 34,
      "nationality": "MX",
      "country": "MX"
    },
    {
      "date": "2026-04-07",
      "gender": "male",
      "age": 53,
      "nationality": "FR",
      "country": "FR"
    },
    {
      "date": "2026-04-07",
      "gender": "male",
      "age": 40,
      "nationality": "IT",
      "country": "IT"
    },
    {
      "date": "2026-04-07",
      "gender": "male",
      "age": 46,
      "nationality": "GB",
      "country": "GB"
    },
    {
      "date": "2026-04-07",
      "gender": "female",
      "age": 50,
      "nationality": "FR",
      "country": "SG"
    },
    {
      "date": "2026-04-07",
      "gender": "male",
      "age": 33,
      "nationality": "IT",
      "country": "IT"
    },
    {
      "date": "2026-04-07",
      "gender": "female",
      "age": 60,
      "nationality": "BE",
      "country": "BE"
    },
    {
      "date": "2026-04-07",
      "gender": "male",
      "age": 65,
      "nationality": "CA",
      "country": "CA"
    },
    {
      "date": "2026-04-07",
      "gender": "female",
      "age": 22,
      "nationality": "PT",
      "country": "PT"
    },
    {
      "date": "2026-04-07",
      "gender": "male",
      "age": 36,
      "nationality": "FR",
      "country": "FR"
    },
    {
      "date": "2026-04-07",
      "gender": "female",
      "age": 65,
      "nationality": "IE",
      "country": "IE"
    },
    {
      "date": "2026-04-08",
      "gender": "female",
      "age": 33,
      "nationality": "ES",
      "country": "ES"
    },
    {
      "date": "2026-04-08",
      "gender": "male",
      "age": 56,
      "nationality": "IN",
      "country": "IN"
    },
    {
      "date": "2026-04-08",
      "gender": "male",
      "age": 51,
      "nationality": "FI",
      "country": "FI"
    },
    {
      "date": "2026-04-08",
      "gender": "male",
      "age": 54,
      "nationality": "IT",
      "country": "IT"
    },
    {
      "date": "2026-04-08",
      "gender": "male",
      "age": 60,
      "nationality": "DE",
      "country": "DE"
    },
    {
      "date": "2026-04-08",
      "gender": "female",
      "age": 51,
      "nationality": "ES",
      "country": "ES"
    },
    {
      "date": "2026-04-08",
      "gender": "male",
      "age": 34,
      "nationality": "PT",
      "country": "PT"
    },
    {
      "date": "2026-04-08",
      "gender": "male",
      "age": 43,
      "nationality": "UA",
      "country": "PT"
    },
    {
      "date": "2026-04-08",
      "gender": "female",
      "age": 32,
      "nationality": "BR",
      "country": "BR"
    },
    {
      "date": "2026-04-09",
      "gender": "female",
      "age": 32,
      "nationality": "VE",
      "country": "MX"
    },
    {
      "date": "2026-04-09",
      "gender": "male",
      "age": 69,
      "nationality": "IT",
      "country": "IT"
    },
    {
      "date": "2026-04-09",
      "gender": "female",
      "age": 45,
      "nationality": "PL",
      "country": "PT"
    },
    {
      "date": "2026-04-09",
      "gender": "male",
      "age": 62,
      "nationality": "IT",
      "country": "IT"
    },
    {
      "date": "2026-04-09",
      "gender": "female",
      "age": 41,
      "nationality": "DE",
      "country": "DE"
    },
    {
      "date": "2026-04-09",
      "gender": "male",
      "age": 40,
      "nationality": "DE",
      "country": "DE"
    },
    {
      "date": "2026-04-09",
      "gender": "male",
      "age": 36,
      "nationality": "PT",
      "country": "PT"
    },
    {
      "date": "2026-04-09",
      "gender": "male",
      "age": 31,
      "nationality": "IN",
      "country": "US"
    },
    {
      "date": "2026-04-09",
      "gender": "female",
      "age": 35,
      "nationality": "IE",
      "country": "IE"
    },
    {
      "date": "2026-04-09",
      "gender": "male",
      "age": 34,
      "nationality": "PT",
      "country": "PT"
    },
    {
      "date": "2026-04-09",
      "gender": "male",
      "age": 52,
      "nationality": "BE",
      "country": "PT"
    },
    {
      "date": "2026-04-09",
      "gender": "male",
      "age": 81,
      "nationality": "IL",
      "country": "IL"
    },
    {
      "date": "2026-04-09",
      "gender": "female",
      "age": 70,
      "nationality": "US",
      "country": "US"
    }
  ]
};
